Added form controls; theme icon map; cleaned up directory structure
hortonworks/fluid-bootstrap-theme pull request #6
Opened 2018-09-04 20:57 UTC by jgolieb

**NOTE: This does NOT include any changes to the fonts or grays based on the email discussion with Houshang.**

- Added form controls, including text inputs with validation examples, fields with button and dropdown add-ons, check boxes, and radio buttons.
- Added a theme-icon map in a new _custom-variables.css which needs to be placed after FontAwesome in the main file.
- Cleaned up the directory structure.
- Some other maintenance to the gulpfile and readme, etc.

2018-09-06 10:08 UTC, tobias-istvan requested changes
I really like that you restructured the folders! I'd go with the BS approach where we can. 👍 
However I added some minor change requests, please let me know what do you think about them.

2018-09-06 10:08 UTC, tobias-istvan commented on src/_variables.scss
>  $grays: ();
I think we can remove these declarations from our `_variables.scss` because they are the same as the original BS one. If we keep them here we have to maintain when they do some changes.
Also I think it is worth to do it now to not to forget it at the end.

2018-09-06 10:08 UTC, tobias-istvan commented on src/_variables.scss
>  //Fluid grays
I really like that you did not just change and override the grays but you use custom variables here. 👍

2018-09-06 10:08 UTC, tobias-istvan commented on src/_variables.scss
>  $theme-colors: () !default;
We should remove the `!default` here, shouldn't we?

2018-09-06 10:08 UTC, tobias-istvan commented on src/_variables.scss
> +$form-feedback-valid-color:         theme-color("success");
Do we need overriding here? I think if you just override the `theme-color()` it will make the work.

2018-09-06 10:08 UTC, tobias-istvan commented on src/components/_alert.scss
> +@each $icon, $value in $theme-icons {
Nice! 👍

2018-09-06 10:08 UTC, tobias-istvan commented on src/components/_forms.scss
> +/*
Maybe we can override the `$input-box-shadow` because it seems that in the Fluid Design there is no any on focus. We should check with the UX guys.

2018-09-06 12:31 UTC, jgolieb commented on src/_variables.scss
>  $grays: ();
I'm not sure what you are referring to here.

2018-09-06 12:33 UTC, jgolieb commented on src/_variables.scss
>  $theme-colors: () !default;
I don't think so. BS takes the approach of declaring an empty map first and then using map-merge() to add the values. So the initial, empty map is not changed from the default.

2018-09-06 12:34 UTC, jgolieb commented on src/_variables.scss
> +$form-feedback-valid-color:         theme-color("success");
Yes, you're right. This was probably left over from something else I tried. I will fix.

2018-09-06 12:35 UTC, jgolieb commented on src/components/_forms.scss
> +/*
Good question.

2018-09-10 12:40 UTC, tobias-istvan approved these changes

2018-09-10 12:43 UTC, merged